# Generated by Django 3.2.7 on 2021-10-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='prenotime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('price', models.FloatField(max_length=100)),
                ('dita', models.CharField(max_length=100)),
                ('ora', models.CharField(max_length=100)),
                ('student', models.CharField(max_length=300)),
            ],
        ),
    ]
